export const SET_IMG_LIST = 'SET_IMG_LIST';
export const SET_IMG_LIST_FILTER = 'SET_IMG_LIST_FILTER'
export const RESET_IMG_LIST_FILTER = 'RESET_IMG_LIST_FILTER'
export const SET_USERS = 'SET_USERS'
export const ADD_USER = 'ADD_USER'

