export const SET_IMG_LIST = 'SET_IMG_LIST';
export const SET_IMG_LIST_FILTER = 'SET_IMG_LIST_FILTER'
export const RESET_IMG_LIST_FILTER = 'RESET_IMG_LIST_FILTER'
export const SET_USERS = 'SET_USERS'
export const SET_USER_LOGED = 'SET_USER_LOGED'
export const ADD_USER = 'ADD_USER'
export const SET_ITEMS_SHOPPING_CART = 'SET_ITEMS_SHOPPING_CART'
